# Dependencies
markdown: redcarpet

# Permalinks
permalink:        pretty

# Server
source:           docs
layouts_dir:      module/_layouts
includes_dir:     module/_includes
collections:      null
destination:      _gh_pages
host:             0.0.0.0
port:             9001
encoding:         UTF-8
baseurl:          /connect-mustache-middleware
